#!/usr/bin/perl -w
#-------------------------------------------------------
# Quick and dirty test script
#-------------------------------------------------------

use strict;
use Data::Walker;

my $s = {

	a => [ 10, 20, "thirty" ],
	b => { 
		"w" => "forty", 
		"x" => "fifty", 
		"y" => 60,
		"z" => \70,
	},
	c => sub { print "I'm a data structure!\n"; },
	d => 80,
};

$s->{e} = \$s->{d};

my $p = Data::Walker->new();
$p->walk($s);

1;
