#!/usr/bin/perl -w
#-------------------------------------------------------
# Quick and dirty test script
#-------------------------------------------------------

use lib '.';
use strict;
use Data::Walker;

my $s;

$s = {

	a => [ 10, 20, 30 ],
	b => { 
		"x" => 10, 
		"y" => 20, 
		"z" => 30 
	},
};

$s->{c} = \$s->{a};

my $p = Data::Walker->new();
$p->walk($s);

1;
